import AppKit
import Combine
import Foundation
import UniformTypeIdentifiers

struct AppServices {
    let openPanelService: OpenPanelServicing
    let studyLoader: StudyLoading
    let diagnosticsStore: DiagnosticLogStore

    static func bootstrap() -> AppServices {
        if let scenario = ProcessInfo.processInfo.environment["OPEN_LUMINA_UI_TEST_SCENARIO"] {
            return UITestAppServices.bootstrap(scenario: scenario)
        }

        let diagnosticsStore = DiagnosticLogStore()
        let openPanelService = OpenPanelService()
        let importer = ISOStudyImporter(diagnosticsStore: diagnosticsStore)
        let parser = StudyCatalogLoader()
        let renderer = DICOMImageRenderer()
        let studyLoader = StudyLoader(importer: importer, parser: parser, renderer: renderer)
        return AppServices(
            openPanelService: openPanelService,
            studyLoader: studyLoader,
            diagnosticsStore: diagnosticsStore
        )
    }
}

protocol OpenPanelServicing {
    @MainActor
    func chooseFolder() -> URL?
    @MainActor
    func chooseISOFile() -> URL?
}

struct OpenPanelService: OpenPanelServicing {
    @MainActor
    func chooseFolder() -> URL? {
        let panel = NSOpenPanel()
        panel.canChooseFiles = false
        panel.canChooseDirectories = true
        panel.allowsMultipleSelection = false
        panel.prompt = "Open Study Folder"
        return panel.runModal() == .OK ? panel.url : nil
    }

    @MainActor
    func chooseISOFile() -> URL? {
        let panel = NSOpenPanel()
        panel.canChooseFiles = true
        panel.canChooseDirectories = false
        panel.allowedContentTypes = [.diskImage]
        panel.allowsMultipleSelection = false
        panel.prompt = "Open Study ISO"
        return panel.runModal() == .OK ? panel.url : nil
    }
}

struct UITestAppServices {
    static func bootstrap(scenario: String) -> AppServices {
        let fixtureRoot = SyntheticStudyFactory.makeUITestFixtureRoot(for: scenario)
        let diagnosticsStore = DiagnosticLogStore()
        let openPanelService = UITestOpenPanelService(root: fixtureRoot, scenario: scenario)
        let importer = MockISOStudyImporter(root: fixtureRoot)
        let parser = StudyCatalogLoader()
        let renderer = DICOMImageRenderer()
        let studyLoader = StudyLoader(importer: importer, parser: parser, renderer: renderer)
        return AppServices(
            openPanelService: openPanelService,
            studyLoader: studyLoader,
            diagnosticsStore: diagnosticsStore
        )
    }
}

struct UITestOpenPanelService: OpenPanelServicing {
    let root: URL
    let scenario: String

    func chooseFolder() -> URL? {
        guard scenario == "folder" else { return nil }
        return root.appendingPathComponent("FolderStudy", isDirectory: true)
    }

    func chooseISOFile() -> URL? {
        guard scenario == "iso" else { return nil }
        return root.appendingPathComponent("MockStudy.iso", isDirectory: false)
    }
}

final class DiagnosticLogStore: ObservableObject {
    @Published private(set) var entries: [DiagnosticLogEntry] = []

    private let formatter = ISO8601DateFormatter()
    private let now: () -> Date
    private let maximumEntries: Int

    init(now: @escaping () -> Date = Date.init, maximumEntries: Int = 400) {
        self.now = now
        self.maximumEntries = maximumEntries
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    }

    func record(_ event: String, details: [String: String] = [:]) {
        let entry = DiagnosticLogEntry(
            timestamp: now(),
            event: sanitizeValue(event),
            details: details
                .sorted { $0.key < $1.key }
                .reduce(into: [:]) { partial, item in
                    partial[item.key] = sanitizeValue(item.value)
                }
        )

        entries.append(entry)
        if entries.count > maximumEntries {
            entries.removeFirst(entries.count - maximumEntries)
        }
    }

    func exportText() -> String {
        var lines = [
            "# OpenLumina Session Diagnostics",
            "# Session-only export generated by explicit user action",
            "# No study contents are included"
        ]

        for entry in entries {
            let timestamp = formatter.string(from: entry.timestamp)
            let detailText = entry.details
                .sorted { $0.key < $1.key }
                .map { "\($0.key)=\($0.value)" }
                .joined(separator: " ")

            if detailText.isEmpty {
                lines.append("[\(timestamp)] \(entry.event)")
            } else {
                lines.append("[\(timestamp)] \(entry.event) \(detailText)")
            }
        }

        return lines.joined(separator: "\n") + "\n"
    }

    func export(to url: URL) throws {
        try exportText().write(to: url, atomically: true, encoding: .utf8)
    }

    private func sanitizeValue(_ raw: String) -> String {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return "n/a" }

        if trimmed.contains("/") || trimmed.contains("\\") {
            return "redacted-path"
        }

        if trimmed.count > 80 {
            return String(trimmed.prefix(77)) + "..."
        }

        return trimmed
    }
}

struct DiagnosticLogEntry: Equatable {
    let timestamp: Date
    let event: String
    let details: [String: String]
}

enum DiagnosticsExportController {
    @MainActor
    static func exportLogs(from store: DiagnosticLogStore) throws -> URL? {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.plainText]
        panel.canCreateDirectories = true
        panel.nameFieldStringValue = suggestedFilename()
        panel.prompt = "Export Logs"

        guard panel.runModal() == .OK, let url = panel.url else {
            return nil
        }

        try store.export(to: url)
        return url
    }

    private static func suggestedFilename() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyyMMdd-HHmmss"
        return "OpenLumina-Diagnostics-\(formatter.string(from: Date())).txt"
    }
}
